[workspace]
members = [ 
    "backend/auth", 
    "backend/database",
    "backend/server",
]

resolver = "2"

[workspace.package]
name = "ids"
version = "0.1.0"
edition = "2021"
rust-version = "1.76"
