[config]
default_to_workspace = false

# ******************* backend *******************
[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.run]
description = "Run 'cargo shuttle run'"
command = "cargo"
args = ["shuttle", "run"]
dependencies = ["fmt"]

[tasks.deploy]
description = "Run 'cargo shuttle deploy'"
command = "cargo"
args = ["shuttle", "deploy"]

[tasks.project_restart]
description = "Run 'cargo project restart'"
command = "cargo"
args = ["shuttle", "project", "restart"]


# ******************* frontend *******************
[tasks.front_dev]
description = "Run 'pnpm run dev' in the frontend directory"
command = "pnpm"
args = ["run", "dev"]
cwd = "./frontend"

[tasks.front_build]
description = "Run 'pnpm run build' in the frontend directory"
command = "pnpm"
args = ["run", "build"]
cwd = "./frontend"

[tasks.front_clean]
# distを空にする
description = "Run 'pnpm run clean' in the frontend directory"
command = "pnpm"
args = ["run", "crean"]
cwd = "./frontend"


# ******************* sqlx-cli *******************
# https://github.com/launchbadge/sqlx/blob/main/sqlx-cli/README.md#enable-building-in-offline-mode-with-query
[tasks.sqlx-cli_install]
command = "cargo"
args = ["install", "sqlx-cli", "--no-default-features", "--features", "native-tls,postgres"]

[tasks.sqlx-migrate-add]
# `cargo make sqlx-migrate-add <file_name>`
description = "Adding migration files for 'up' and 'down'"
command = "sqlx"
args = ["migrate", "add", "-r", "--source", "./backend/database/migrations", "${@}"]

[tasks.sqlx-migrate-run]
command = "sqlx"
args = ["migrate", "run", "--source", "./backend/database/migrations"]

[tasks.sqlx-migrate-revert]
# (注)ロールバック
command = "sqlx"
args = ["migrate", "revert", "--source", "./backend/database/migrations"]

