[package]
name = "ids_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true, features = [ "typed-header" ]}
axum-macros = { workspace = true }
shuttle-axum = { workspace = true }
shuttle-runtime = { workspace = true }
shuttle-shared-db = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
dotenvy = { workspace = true }
envy = { workspace = true }
tower-http = { workspace = true, features = [ "trace", "fs", "cors" ] }
tracing = { workspace = true }
chrono = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
tower = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

ids_auth = { path = "../auth/" }
ids_database = { path = "../database/" }
ids_shared = {path = "../shared/"}

[dev-dependencies]
fake = { workspace = true }
mime = { workspace = true }
rstest = { workspace = true }